name: Fetch Gist Post

on:
  # push:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{secrets.GIST_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install requests

      - name: Create blogs
        run: python build.py

      - name: Check results
        run: ls -al ./blog

      - name: Save result
        run: |
          mkdir -p /tmp/architecture
          cp -r ./* /tmp/architecture
          rm -rf ./blog/*

          # Check if 'gh-pages' branch exists
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git fetch origin gh-pages:gh-pages
            git checkout gh-pages
            git pull
          else
            git checkout -b gh-pages
          fi

          git config user.email "autodeploy@github.com"
          git config user.name "github action auto bot"

      - name: Deploy to GitHub Pages
        run: |
          rm -rf *
          cp -r /tmp/architecture/* ./
          git add .
          
          # Check if anything is deleted
          if git status --porcelain | grep '^ D'; then
            git rm $(git status --porcelain | grep '^ D' | cut -d' ' -f2)
          fi
          
          git commit -m "Release new post"
          git push origin gh-pages